package com.encrypt.demo.domain;

public class TbRsaDemo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rsa_demo.id
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rsa_demo.name
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rsa_demo.rsaPublicKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    private String rsapublickey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rsa_demo.rsaPrivateKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    private String rsaprivatekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rsa_demo.aesKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    private String aeskey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rsa_demo.id
     *
     * @return the value of tb_rsa_demo.id
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rsa_demo.id
     *
     * @param id the value for tb_rsa_demo.id
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rsa_demo.name
     *
     * @return the value of tb_rsa_demo.name
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rsa_demo.name
     *
     * @param name the value for tb_rsa_demo.name
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rsa_demo.rsaPublicKey
     *
     * @return the value of tb_rsa_demo.rsaPublicKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public String getRsapublickey() {
        return rsapublickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rsa_demo.rsaPublicKey
     *
     * @param rsapublickey the value for tb_rsa_demo.rsaPublicKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public void setRsapublickey(String rsapublickey) {
        this.rsapublickey = rsapublickey == null ? null : rsapublickey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rsa_demo.rsaPrivateKey
     *
     * @return the value of tb_rsa_demo.rsaPrivateKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public String getRsaprivatekey() {
        return rsaprivatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rsa_demo.rsaPrivateKey
     *
     * @param rsaprivatekey the value for tb_rsa_demo.rsaPrivateKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public void setRsaprivatekey(String rsaprivatekey) {
        this.rsaprivatekey = rsaprivatekey == null ? null : rsaprivatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rsa_demo.aesKey
     *
     * @return the value of tb_rsa_demo.aesKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public String getAeskey() {
        return aeskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rsa_demo.aesKey
     *
     * @param aeskey the value for tb_rsa_demo.aesKey
     *
     * @mbg.generated Thu Jan 13 17:43:28 KST 2022
     */
    public void setAeskey(String aeskey) {
        this.aeskey = aeskey == null ? null : aeskey.trim();
    }
}